### PR TITLE
Fix for: can't convert Symbol to String when the code executes klass.class_eval(var) 

### PR DESCRIPTION
**Pull request by tispratik**
Hi noeticpenguin,

I encountered this issue when upgrading my rails 2.3.11 app from ruby 1.8 to 1.9.

Thanks,
Pratik Khadloya

### CODE REVIEW

**Comment by noeticpenguin** [comment]
Pratik, Can you give me some more context on this? I'm assuming you're using my fork of soap4r? Can I see the full stack trace? Lets get this fixed!

**Comment by tispratik** [comment]
Yes i used your fork of soap4r. Sorry, i did not save the stack trace for the "can't convert Symbol to String" error. And the other two commits (11035d3 and f2dd3d9) for Ruby1.9 fixes are just analytical fixes from my knowledge about the differences between Ruby1.8 and Ruby1.9

**Comment by noeticpenguin** [comment]
I'm not sure what commits you're looking at ? I don't see commits with those #'s in my repo.

How can I duplicate this issue?

**Comment by mattrose** [comment]
Hmm, I hit this issue as well.  I just upgraded from 1.8 to 1.9 and commit 5637ef1 fixed the issue I was having.  Do you want me to fork the repo and commit this fix again?

**Comment by noeticpenguin** [comment]
Yes please do! I will merge ASAP after pull request

-------- Original Message --------
From: mattrose
Sent: Thu, 21/06/2012 16:07
To: Kevin Poorman
CC:
Subject: Re: [soap4r-noeticpenguin] Fix for: can't convert Symbol to
String when the code executes klass.class_eval(var) (#1)
Hmm, I hit this issue as well.  I just upgraded from 1.8 to 1.9 and
commit 5637ef1 fixed the issue I was having.  Do you want me to fork
the repo and commit this fix again?

---

**Pull request closed without merging**
